@baseUrl = http://localhost:3000


### Create user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "usuario":"ulises",
    "password":"123",
    "nombre":"omar",
    "role":"1"
}

### Login whit user_name
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "usuario":"ulises",
    "password":"123"
}